### ISSUE TITLE
Пункт 3.1.1

### ISSUE THREAD

**Issue by AJIOB** [BlackFox147/HeapOfBooks#1]
Это требование к GUI. Сами функции нужно оставить, но распределять их по кнопкам еще рано (Mockup - набросок GUI, а не его один из конечных вариантов)
Относится к 3.1.1, 3.1.2, 3.1.3

**Comment by AJIOB** [comment]
Переоформлено. Смотреть #4

**Comment by BlackFox147** [comment]
Исправила. 
#4
