### ISSUE TITLE
Добавить глоссарий

### ISSUE THREAD

**Issue by AJIOB** [BlackFox147/HeapOfBooks#2]
Коллекций чего? Бананов? Или апельсинов? Рекомендуется создать глоссарий
Относится к:
- [этому](https://github.com/BlackFox147/HeapOfBooks/commit/cdf68965c3e50ca9eacf741830b1c0ba61bf5630#diff-bb8505f166d1fdafe3ffca41e471622fR59)
- [этому](https://github.com/BlackFox147/HeapOfBooks/commit/cdf68965c3e50ca9eacf741830b1c0ba61bf5630#diff-bb8505f166d1fdafe3ffca41e471622fR80)

**Comment by BlackFox147** [comment]
Добавленно в введении.
[изменения](https://github.com/BlackFox147/HeapOfBooks/commit/9591bccebf204b486b3a16b744cbdca0732e7aba)

**Comment by AJIOB** [comment]
Переоткройте, пожалуйста, баг. Он не был исправлен. Когда читаешь требования, не всегда понятно, что за коллекции имеются ввиду в пункте 3.1.1 [тут](https://github.com/BlackFox147/HeapOfBooks/blob/master/Documentation/Requirements.md#31-%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F). Измените, пожалуйста, фразу (расшифруйте ее) или удалите

**Comment by BlackFox147** [comment]
Дочитайте, пожалуйста предложение до конца.
[ссылка](https://github.com/BlackFox147/HeapOfBooks/commit/9591bccebf204b486b3a16b744cbdca0732e7aba#diff-bb8505f166d1fdafe3ffca41e471622fR7)

**Comment by AJIOB** [comment]
Извините, не заметил. Тогда согласуйте, пожалуйста, фразу в той же строке "пользовательские коллекциями текстовых документов"
