### ISSUE TITLE
Корректно оформить документацию

### ISSUE THREAD

**Issue by AJIOB** [BlackFox147/HeapOfBooks#3]
Перенести [эти](https://github.com/BlackFox147/HeapOfBooks/commit/f4756a06183bed18fe4de267ff85c51ad67a0486#diff-bb8505f166d1fdafe3ffca41e471622fR8) пункты в функциональные требования.

**Comment by BlackFox147** [comment]
Я не совсем согласна, что их нужно переносить в  функциональные требования. Скорее, просто убрать из введения. 
[изменения](https://github.com/BlackFox147/HeapOfBooks/commit/9591bccebf204b486b3a16b744cbdca0732e7aba)
