### ISSUE TITLE
Корректно оформить требования к интерфейсу пользователя

### ISSUE THREAD

**Issue by AJIOB** [BlackFox147/HeapOfBooks#4]
Требуется перенести [эти](https://github.com/BlackFox147/HeapOfBooks/commit/cdf68965c3e50ca9eacf741830b1c0ba61bf5630#diff-bb8505f166d1fdafe3ffca41e471622fR50) пункты в раздел "Интерфейс пользователя" или аналогичный

**Comment by BlackFox147** [comment]
Эти пункты были вообще не нужны. Полностью изменила.
[изменения](https://github.com/BlackFox147/HeapOfBooks/commit/514bf67d2d64c3550c48fc519718cdf4daf0eb2e#diff-bb8505f166d1fdafe3ffca41e471622fR50)
