### ISSUE TITLE
Корректно оформить функциональные и нефункциональные требования

### ISSUE THREAD

**Issue by AJIOB** [BlackFox147/HeapOfBooks#5]

**Comment by BlackFox147** [comment]
Функциональные исправила, а вот с нефункциональными и так всё в порядке. Я сейчас не вижу причин их изменять.
[изменения](https://github.com/BlackFox147/HeapOfBooks/commit/514bf67d2d64c3550c48fc519718cdf4daf0eb2e#diff-bb8505f166d1fdafe3ffca41e471622fR50)
